title: James Lu # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  As a data scientist, I have worked on a variety of projects that demonstrate my skills in data engineering, data analysis, machine learning, and visualization.
  These are some projects I have undertaken including some key insights and deliverables from each.
  <br><br>
  Currently I am honing and expanding my skillset in data analytics/science with data visualisation and cloud technologies. I am also an active Lead in the Google Student Developer Club at UNSW where I work with a team to create tech-focused events for students.
  Please feel free to contact me for further details. 
  <br><br>
  <a href="https://www.linkedin.com/in/jameslu-DS/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
